version: "3.8"
services:
  mysql_service:
    image: mysql
    container_name: mysql_container
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mincheolkang34
      MYSQL_USER: mincheolkang34
      MYSQL_PASSWORD: 1234
    volumes:
      - C:/db/mysql/data:/var/lib/mysql