version: "3.8"
services:
  spring_app_service:
    build: .
    container_name: spring_app_container
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_service
    volumes:
      - ./ch04-0.0.1-SNAPSHOT.jar:/app/app.jar
  
  mysql_service:
    image: mysql 
    container_name: mysql_container
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mincheolkang34
      MYSQL_USER: mincheolkang34
      MYSQL_PASSWORD: 1234